export const proyectosData = [
  {
    title: "Weather Channel",
    subtitle: "JavaScript, bootstrap",
    description: "¿Quieres saber cómo va a estar el clima en la ciudad?",
    imageUrl: "/assets/proyecto/clima.png",
    stack: "JavaScript, bootstrap",
    link: "https://appclimaapp.netlify.app/",
    type: "app",
  },
  {
    title: "Color Game",
    subtitle: "JavaScript, bootstrap",
    description: "Juego donde tendrás que adivinar un color al azar",
    imageUrl: "/assets/proyecto/color.png",
    stack: "JavaScript, bootstrap",
    link: "https://color-game-pledu.netlify.app/",
    type: "app",
  },
  {
    title: "No me cagues",
    subtitle: "JavaScript, bootstrap",
    description:
    "Calculadora de sueldo basada en una forma de pago en particular",
    imageUrl: "/assets/proyecto/noMeCagues.png",
    stack: "JavaScript, bootstrap",
    link: "https://nomecagues1.netlify.app/",
    type: "app",
  },
  {
    title: "Rick and Morty",
    subtitle: "JavaScript, react, bootstrap",
    description: "Toda la informacion de los personajes de la serie",
    imageUrl: "/assets/proyecto/rick.png",
    stack: "JavaScript, react, bootstrap",
    link: "https://animated-travesseiro-528f40.netlify.app/",
    type: "web",
  },
  {
    title: "Pokemon Card",
    subtitle: "JavaScript, bootstrap",
    description: "Encuentra a tu pokemon favorito en esta aplicación",
    stack: "JavaScript, bootstrap",
    imageUrl: "/assets/proyecto/pokeAPI.png",
    link: "https://glistening-horse-b219d1.netlify.app/",
    type: "web",
  },
  {
    title: "Super Hero App",
    subtitle: "typescript, ionic, angular",
    description: "App Mobile, guarda y comparte tus super héroes favoritos",
    imageUrl: "/assets/proyecto/super.png",
    stack: "typescript, ionic, angular",
    link: "https://proyecto-ionic-grupo10.vercel.app/login",
    type: "app",
  },
  {
    title: "Tienda Funko",
    subtitle: "JavaScript, ejs, nodejs, express, mysql, bootstrap",
    description: "Tienda online de figuras coleccionables FUNKOPOP!",
    imageUrl: "/assets/proyecto/funko.png",
    stack: "JavaScript, ejs, nodejs, express, mysql, bootstrap",
    link: "https://funko-rjpr33bic-juan-s-projects-00876b1f.vercel.app/",
    type: "web",
  },
  {
    title: "Patitas al Rescate",
    subtitle: "typescript, angular, bootstrap",
    description:
    "Publica un anuncio de tu mascota perdida y encuentra a tu mascota",
    imageUrl: "/assets/proyecto/patitasAlRescate.png",
    stack: "typescript, angular, java, spring , mysql",
    link: "https://patitas-al-rescate.vercel.app/home",
    type: "web",
  },
  {
    title: "Soy Juan",
    subtitle: "JavaScript, react, bootstrap",
    description: "LandingPage personal",
    imageUrl: "/assets/proyecto/soyJuan.png",
    stack: "JavaScript, react, bootstrap",
    link: "https://soyjuan.netlify.app/",
    type: "web",
  },
  {
    title: "Sidebar",
    subtitle: "JavaScript, react, styled-components",
    description: "Sidebar perzonalizado, con animaciones y modo claro/oscuro",
    imageUrl: "/assets/proyecto/sidebar.png",
    stack: "JavaScript, react, styled-components",
    link: "https://pagesidebar.netlify.app/",
    type: "web",
  },
  {
    title: "Sistema de Gestion",
    subtitle: "JavaScript, react, material-ui",
    description: "Sistema de gestion para consultorio odontologico",
    imageUrl: "/assets/proyecto/odontologia.png",
    stack: "JavaScript, react, material-ui",
    link: "",

  }
  // {
  //   title: "Odontologia",
  //   subtitle: "JavaScript, react, material-ui",
  //   description: "LandingPage para consultorio odontologico",
  //   imageUrl: "/assets/proyecto/",
  //   stack: "JavaScript, react, material-ui",
  //   link: "",

  // }
  
];
