export const proyectosData = [
  {
    title: "Weather Channel",
    subtitle: "JavaScript, bootstrap",
    description: "¿Quieres saber cómo va a estar el clima en la ciudad?",
    imageUrl: "/assets/proyecto/clima.png",
    stack: "JavaScript, bootstrap",
    link: "https://appclimaapp.netlify.app/",
    type: "app",
  },
  {
    title: "Color Game",
    subtitle: "JavaScript, bootstrap",
    description: "Juego donde tendrás que adivinar un color al azar",
    imageUrl: "/assets/proyecto/color.png",
    stack: "JavaScript, bootstrap",
    link: "https://color-game-pledu.netlify.app/",
    type: "app",
  },
  {
    title: "No me cagues",
    subtitle: "JavaScript, bootstrap",
    description:
    "Calculadora de sueldo basada en una forma de pago en particular",
    imageUrl: "/assets/proyecto/",
    stack: "JavaScript, bootstrap",
    link: "https://nomecagues1.netlify.app/",
    type: "app",
  },
  {
    title: "Rick and Morty",
    subtitle: "JavaScript, react, bootstrap",
    description: "Toda la informacion de los personajes de la serie",
    imageUrl: "/assets/proyecto/rick.avif",
    stack: "JavaScript, react, bootstrap",
    link: "https://animated-travesseiro-528f40.netlify.app/",
    type: "web",
  },
  {
    title: "Pokemon Card",
    subtitle: "JavaScript, bootstrap",
    description: "Encuentra a tu pokemon favorito en esta aplicación",
    stack: "JavaScript, bootstrap",
    imageUrl: "/assets/proyecto/poke.avif",
    link: "https://glistening-horse-b219d1.netlify.app/",
    type: "web",
  },
  {
    title: "Super Hero App",
    subtitle: "typescript, ionic, angular",
    description: "App Mobile, guarda y comparte tus super héroes favoritos",
    imageUrl: "/assets/proyecto/",
    stack: "typescript, ionic, angular",
    link: "https://proyecto-ionic-grupo10.vercel.app/login",
    type: "app",
  },
  {
    title: "Tienda Funko",
    subtitle: "JavaScript, ejs, nodejs, express, mysql, bootstrap",
    description: "Tienda online de figuras coleccionables FUNKOPOP!",
    imageUrl: "/assets/proyecto/pop.jpg",
    stack: "JavaScript, ejs, nodejs, express, mysql, bootstrap",
    link: "https://funko-rjpr33bic-juan-s-projects-00876b1f.vercel.app/",
    type: "web",
  },
  {
    title: "Patitas al Rescate",
    subtitle: "typescript, angular, bootstrap",
    description:
    "Publica un anuncio de tu mascota perdida y encuentra a tu mascota",
    imageUrl: "/assets/proyecto/",
    stack: "typescript, angular, java, spring , mysql",
    link: "https://patitas-al-rescate.vercel.app/home",
    type: "web",
  },
  {
    title: "Soy Juan",
    subtitle: "JavaScript, react, bootstrap",
    description: "LandingPage personal",
    imageUrl: "/assets/proyecto/landing.png",
    stack: "JavaScript, react, bootstrap",
    link: "https://soyjuan.netlify.app/",
    type: "web",
  },
  {
    title: "Sidebar",
    subtitle: "JavaScript, react, styled-components",
    description: "Sidebar perzonalizado, con animaciones y modo claro/oscuro",
    imageUrl: "/assets/proyecto/landing.png",
    stack: "JavaScript, react, styled-components",
    link: "https://pagesidebar.netlify.app/",
    type: "web",
  },
  {
    title: "Odontologia",
    subtitle: "JavaScript, react, material-ui",
    description: "LandingPage para consultorio odontologico",
    imageUrl: "/assets/proyecto/odontologia.png",
    stack: "JavaScript, react, material-ui",
    link: "",

  },{
    title: "Sistema para consultorio odontologico",
    subtitle: "JavaScript, react, material-ui, firebase",
    description: "Sistema para gestion de pacientes, historias clinicas, agenda y más..",
    imageUrl: "/assets/proyecto/odontologia.png",
    stack: "JavaScript, react, material-ui, firebase",
    link: "",

  }
  
];
